# Generated by Django 5.2.7 on 2025-11-04 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_productmodelstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_on_sale',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='ProductModelStock',
        ),
    ]
