# Generated by Django 5.2.7 on 2025-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_logo_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='Example short description', max_length=255),
            preserve_default=False,
        ),
    ]
