# Generated by Django 5.2.7 on 2025-11-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productmodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizestock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsizestock',
            name='size',
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcolour')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsize')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductColourStock',
        ),
        migrations.DeleteModel(
            name='ProductSizeStock',
        ),
    ]
