# Generated by Django 5.2.7 on 2025-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productsizestock_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolour',
            name='picture',
            field=models.ImageField(null=True, upload_to='colours/'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='picture',
            field=models.ImageField(null=True, upload_to='materials/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to='models/'),
        ),
        migrations.AddField(
            model_name='productseason',
            name='picture',
            field=models.ImageField(null=True, upload_to='season/'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='picture',
            field=models.ImageField(null=True, upload_to='types/'),
        ),
    ]
