# Generated by Django 5.2.7 on 2025-11-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productmodel_brand'),
        ('products', '0006_alter_product_short_description'),
    ]

    operations = [
    ]
