# Generated by Django 5.2.7 on 2025-11-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productsizestock_product_and_more'),
        ('products', '0007_merge_20251107_1337'),
    ]

    operations = [
    ]
