# Generated by Django 5.2.7 on 2025-11-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcolour_picture_productmaterial_picture_and_more'),
        ('products', '0008_merge_20251107_1408'),
    ]

    operations = [
    ]
