# Generated by Django 5.2.7 on 2025-11-18 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_material_alter_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productmodel'),
        ),
    ]
