# Generated by Django 5.2.7 on 2025-11-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_remove_displaycase_article_delete_article_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
