# Generated by Django 5.2.7 on 2025-11-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_colour'),
        ('products', '0011_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='colour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productcolour'),
            preserve_default=False,
        ),
    ]
