# Generated by Django 5.2.7 on 2025-11-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='red', max_length=30),
            preserve_default=False,
        ),
    ]
