# Generated by Django 5.2.7 on 2025-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_color_orderitem_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'En proceso'), ('SH', 'Enviado'), ('DE', 'Entregado'), ('CA', 'Cancelado')], default='PE'),
        ),
    ]
