# Generated by Django 5.2.7 on 2025-11-18 20:56

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=users.models.AppUser),
        ),
    ]
