# Generated by Django 5.2.7 on 2025-11-19 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('PE', 'Pendiente de pago'), ('PR', 'En proceso'), ('SH', 'Enviado'), ('DE', 'Entregado'), ('CA', 'Cancelado')], default='PE'),
        ),
    ]
