# Generated by Django 5.2.7 on 2025-11-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('SP', 'En tienda'), ('HD', 'A domicilio')], null=True),
        ),
    ]
