# Generated by Django 5.2.7 on 2025-11-19 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_client_email_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
