# Generated by Django 5.2.7 on 2025-11-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_client_email'),
        ('orders', '0014_order_type'),
    ]

    operations = [
    ]
