# Generated by Django 5.2.7 on 2025-11-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_merge_0014_alter_order_client_email_0014_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
