# Generated by Django 5.2.7 on 2025-11-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_merge_0014_alter_order_client_email_0014_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
