# Generated by Django 5.2.7 on 2025-11-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_tracking_number'),
        ('orders', '0016_remove_order_email'),
    ]

    operations = [
    ]
