# Generated by Django 5.2.7 on 2025-11-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_merge_20251121_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_percentage',
        ),
    ]
