# Generated by Django 5.2.7 on 2025-11-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_deliverycost'),
        ('orders', '0018_remove_order_discount_percentage'),
    ]

    operations = [
    ]
